paths:
  .github/workflows/**/*.{yml,yaml}:
    ignore:
      - '"paths" section must be sequence node but got alias node with "" tag'
  .github/workflows/pyinstaller.yaml:
    ignore:
      - "shellcheck reported issue in this script"
